In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import scipy.stats as stats



import datetime

In [4]:
other_train = pd.read_csv("dataset/other_train.csv")
other_valid = pd.read_csv("dataset/other_valid.csv")
personal_train = pd.read_csv("dataset/personal_train.csv")
personal_valid = pd.read_csv("dataset/personal_valid.csv")

In [5]:
other_train.head()

,Unnamed: 0,name,address,kurtosis_oxygen,pregnant,education-num,relationship,skewness_glucose,mean_glucose,std_oxygen,...,kurtosis_glucose,personal_info,education,fnlwgt,class,std_glucose,income,mean_oxygen,hours-per-week,capital-loss
0,0,Mathew Johnson,32873 Michelle Prairie Apt. 196\r\nNew Jessica...,1.429773,f,9.0,Not-in-family,0.127060565,157.664062,43.672966,...,-0.728489,Craft-repair|United-States\r\r\nNever-married ...,HS-grad,208862.0,0.0,54.374896,<=50K,28.038462,40.0,0.0
1,1,Ronald Lange,"30973 Martinez Shores\r\nJameston, CA 70245",9.086361,f,10.0,Unmarried,-0.279978339,117.875000,15.103930,...,0.171736,Adm-clerical|United-States\r\r\nDivorced -- Pr...,Some-college,109015.0,0.0,54.222775,<=50K,2.596154,40.0,0.0
2,2,Larry Seider,"919 Austin Wall\r\nJessicaview, MO 33808",8.666514,f,9.0,Husband,0.230722264,109.937500,15.166792,...,0.262268,Other-service|United-States\r\r\nMarried-civ-s...,HS-grad,137674.0,0.0,46.742605,<=50K,2.566054,40.0,0.0
3,3,Thomas Wise,"39041 Graham Freeway\r\nJeanettefort, AK 59160",17.251642,f,9.0,Unmarried,0.867791138,98.882812,13.941180,...,0.529013,Exec-managerial|United-States\r\r\nDivorced --...,HS-grad,97453.0,0.0,-4083.036957,<=50K,0.806856,40.0,0.0
4,4,Marion Bursey,"85508 Martin Villages\r\nJonathanshire, AL 29047",7.788552,f,9.0,Not-in-family,1.746993878,92.031250,16.477481,...,0.694631,Other-service|United-States\r\r\nDivorced -- P...,HS-grad,191088.0,0.0,39.015609,<=50K,2.987458,52.0,1741.0